repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/mtkennerly/pre-commit-hooks
    rev: v0.1.0
    hooks:
      - id: poetry-black
      - id: poetry-flake8
      - id: poetry-mypy
